refactor: Fix database drop and recreate errors in db-flask script

diff --git a/db-flask b/db-flask
--- a/db-flask
+++ b/db-flask
@@ -30,19 +30,28 @@ trap kill_server EXIT
 # drop the existing database
 echo "NOTE: Dropping the 'hbnb_dev_db' database..."
 
-echo "drop database if exists hbnb_dev_db;" | sudo mysql
+if ! echo "drop database if exists hbnb_dev_db" | sudo mysql; then
+	echo "Failed to drop the database"
+	exit 1
+fi
 
 # use the setup script to create it again before generating new data
 echo "Recreating the database, stand by..."
 
 sudo cat setup_mysql_dev.sql | mysql || :
+command_status=$?
+
+if [[ $command_status -ne 0 ]]; then
+	echo "Failed to recreate the database"
+	exit 1
+fi
 
 sleep 2
 
 echo "Starting Flask Server"
 
 while true; do
-	if ! pgrep -laf "python3 -m ${flask_app}" &> /dev/null; then
+	if ! pgrep -laf "python3 -m ${flask_app}" &>/dev/null; then
 		HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd \
 			HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db \
 			HBNB_TYPE_STORAGE=db HBNB_API_HOST=0.0.0.0 HBNB_API_PORT=5002 \
